version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-faq
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin  

  redis:
    image: redis:latest
    container_name: redis-faq
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongodb_data:
  redis_data:
